inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'spec/**/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'config/routes.rb'
    - 'app/helpers/application_helper.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'
